### ISSUE TITLE
Missing inventoryIcon for avaliemblembig

### ISSUE THREAD

**Issue by Thundercraft** [Fevix/Avali#247] opened 2016-07-31 13:34 UTC
The following in my Starbound log concerned me:

`[08:09:15.460] [Warn] Missing inventoryIcon for avaliemblembig, using default`

Is there a missing inventory icon for avaliemblembig?

[AvaliEmblemBig.starbound.log.zip](https://github.com/Fevix/Avali/files/392426/AvaliEmblemBig.starbound.log.zip)

**Comment by ChangelingRain** [comment] 2016-07-31 14:18
#246 
Or in other words, yes.

**Comment by UlithiumDragon** [comment] 2016-07-31 17:46
I noticed this as well. The object crafts and places correctly, but the "small" image used as the inventory icon is broken at the moment - it shows the standard "white X" used for missing icons.

I swear I've seen this working since the 1.0 update, too.

**Comment by Fevix** [comment] 2016-07-31 19:05
@UlithiumDragon You and me both. I've USED the big emblem in the 1.0 update, and only recently changed it over to the small emblem's png for the icon hoping it would work. (The small emblem uses that same png with no issue, no?)

Also, this is a duplicate of #246 so I'm going to close this issue. Please focus replies to that issue.

**Closed by Fevix** 2016-07-31 19:05 UTC
