### ISSUE TITLE
JsonPatchException - gunwarning1

### ISSUE THREAD

**Issue by AllSystemsGo** [Fevix/Avali#120] opened 2015-12-20 18:14 UTC
[19:51:06.861] Error: Could not apply patch from backend: Folder <../giraffe_storage/mods/Avali-2.3.0/.>.  Caused by: (JsonPatchException) Could not apply patch to base. (JsonPatchException) Could not apply operation to base. (TraversalException) No such key 'gunwarning1' in pathApply("/gunwarning1/avali")

(this happens at runtime, not startup)

**Comment by Fevix** [comment] 2015-12-25 09:04
5c86e73f9f215866521cc397ac5642a1caa7dd15 contains an attempted fix. Please update and attempt to reproduce error

**Comment by Fevix** [comment] 2016-01-21 08:47
It's been almost 4 weeks since the last update to this. I'm closing it.

**Closed by Fevix** 2016-01-21 08:47 UTC
