### ISSUE TITLE
Villager die when I talk to them.

### ISSUE THREAD

**Issue by LagiaDOS** [Fevix/Avali#190] opened 2016-07-26 06:46 UTC
title.
When I go to a village and talk to anyone, they just explode. Right now I have onñy found floran, glitch and avian villages, all of them have had the same result.

**Comment by Fevix** [comment] 2016-07-27 07:40
Replicate this error then send me your starbound.log file please.

**Comment by Reysor** [comment] 2016-07-27 08:26
Oh, we had this kind of problem too. We manually updated the old Kemono Mod and forgot one clip in the dialog file. Everytime we wanted to speak to an villager, they exploded in an blue light. And even if we did not play a Kemono.

So maybe checking the dialog file could help.

Sincerely,
Rey

**Comment by Fevix** [comment] 2016-07-27 09:00
What was the issue in that file so I can address it her?

**Comment by Reysor** [comment] 2016-07-27 17:37
Well... it was just a typing mistake. So I can not really tell where the problem in the dialog file with the Avali is. It's like to find a drop of oil in the ocean, random.

Or... just to forget something while programming and then you need to look everything over and over again... :/

**Comment by Ronsemberg** [comment] 2016-07-28 09:55
I replicated this issue myself just about now. Appears to be indeed caused by a failed update to the behaviour.lua script, cause is failure to load dialog/guard.config:hail
From my .log file:

[Error] Exception while invoking lua function 'update'. (LuaException) Error code 2, [string "/scripts/behavior.lua"]:185: [cooldown] error: [string "/scripts/behavior.lua"]:185: [sequence] error: [string "/scripts/behavior.lua"]:185: [succeeder] error: [string "/scripts/behavior.lua"]:185: [sequence] error: [string "/scripts/behavior.lua"]:178: [sayToEntity] error: [string "/scripts/actions/dialog.lua"]:18: (AssetException) Error loading asset /dialog/guard.config:hail

This is my actual .log file.

[starbound.txt](https://github.com/Fevix/Avali/files/388095/starbound.txt)

**Comment by Fevix** [comment] 2016-07-28 22:47
Attempted fix is incoming in near future.

**Comment by Fevix** [comment] 2016-07-30 07:01
Issue has been confirmed resolved by various parties. Please reopen if this is not the case.

**Closed by Fevix** 2016-07-30 07:01 UTC
