### ISSUE TITLE
Npc's are dying when i install mod. 

### ISSUE THREAD

**Issue by Lethani** [Fevix/Avali#218] opened 2016-07-28 21:37 UTC
think its mainly the guards, never done this stuff before so hopefully sent log across okay....

https://drive.google.com/open?id=0B7W68g1z8yZcZk9fNEUyaVU2NFU

**Comment by Fevix** [comment] 2016-07-28 22:52
Duplicate of #190

**Closed by Fevix** 2016-07-28 22:52 UTC
Labels: duplicate
