### ISSUE TITLE
chest spawn error

### ISSUE THREAD

**Issue by AllSystemsGo** [Fevix/Avali#119] opened 2015-12-20 18:13 UTC
[19:50:40.360] Error: Could not instantiate item '[avaliguardtier2chest, 1, {"seed":-1762924713560738429,"colorIndex":3}]'. (JsonException) Could not find 'baseMultiplier' or 'effectiveMultiplier' or 'amount' element in stat effect config
[19:50:43.059] Error: Could not instantiate item '[avaliguardtier2chest, 1, {"seed":-6177224883388041414,"colorIndex":3}]'. (JsonException) Could not find 'baseMultiplier' or 'effectiveMultiplier' or 'amount' element in stat effect config
[19:50:43.065] Error: Could not instantiate item '[avaliguardtier2chest, 1, {"seed":7957288894284665399,"colorIndex":3}]'. (JsonException) Could not find 'baseMultiplier' or 'effectiveMultiplier' or 'amount' element in stat effect config
[19:50:43.074] Error: Could not instantiate item '[avaliguardtier2chest, 1, {"seed":-1762924713560738429,"colorIndex":3}]'. (JsonException) Could not find 'baseMultiplier' or 'effectiveMultiplier' or 'amount' element in stat effect config
[19:50:49.444] Warn: Failed to place dungeon object: tombthing3 direction: 1 position: (1381, 767)

(There's actually a number of placement errors for tombthing stuff, but that's probably not urgent--just means dungeons won't appear quite as designed)

**Comment by Fevix** [comment] 2015-12-25 09:04
Please update and attempt to reproduce

**Comment by Fevix** [comment] 2016-01-21 08:46
It's been almost 4 weeks since the last update to this. I'm closing it.

**Closed by Fevix** 2016-01-21 08:46 UTC
